# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            The Enterprise Blueprint
tagline:          'An interview series on toughest problems facing the enterprise'
description:      'An interview series on the toughest technology problems facing the enterprise and the people who work tirelessly to solve them'
url:              http://archbhise.github.io/enterpriseblueprint/
baseurl:          "/enterpriseblueprint/"

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/archbhise/enterpriseblueprint

plugins: [jekyll-paginate]